'use strict';
const $=id=>document.getElementById(id);let data={items:[],fixtures:[]},active=null;
async function api(path,method='GET',body){const response=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const value=await response.json();if(!response.ok)throw Error(typeof value.detail==='string'?value.detail:'Проверьте параметры запроса');return value}
function message(text){$('message').textContent=text}
function preview(){const item=data.fixtures.find(x=>x.id===$('fixture').value);$('preview').textContent=item?.text||''}
function renderHistory(){const container=$('history');container.replaceChildren();if(!data.items.length){container.textContent='Материалы ещё не обработаны.';return}for(const item of data.items){const button=document.createElement('button');button.textContent=item.fixture.title;const small=document.createElement('small');small.textContent=(item.status==='failed'?'Ошибка извлечения':'Черновик готов')+' · '+new Date(item.created_at).toLocaleTimeString('ru');button.append(small);button.onclick=()=>show(item);container.append(button)}}
function show(item){active=item;$('empty').hidden=true;$('result').hidden=false;$('result-title').textContent=item.fixture.title;$('stages').replaceChildren();for(const stage of item.stages){const node=document.createElement('div');node.className='stage '+(stage.state==='failed'?'failed':'');node.textContent=(stage.state==='done'?'✓ ':'! ')+stage.name;const span=document.createElement('span');span.textContent=stage.error||stage.ms+' мс · серверное измерение';node.append(span);$('stages').append(node)}$('retry').hidden=item.status!=='failed';$('extraction').replaceChildren();const text=document.createElement('p');text.textContent=item.extracted?.extracted_text||item.processed.clean_text;$('extraction').append(text);for(const value of ['Язык: '+item.processed.language,'Слов: '+item.processed.word_count,'URL: '+item.processed.url_count,'Метод: '+(item.extracted?.extraction_method||'не выполнен')]){const tag=document.createElement('span');tag.className='tag';tag.textContent=value;$('extraction').append(tag)}$('classification-section').hidden=!item.classification;$('draft-section').hidden=!item.draft;$('classification').replaceChildren();if(item.classification){const note=document.createElement('p');note.textContent='Категория: '+item.classification.label+'. '+item.classification.limitation;$('classification').append(note);for(const[label,value]of Object.entries(item.classification.scores)){const row=document.createElement('div');row.className='score';const name=document.createElement('label');name.textContent=label;const bar=document.createElement('progress');bar.max=1;bar.value=value;bar.setAttribute('aria-label',label);const score=document.createElement('span');score.textContent=value.toFixed(3);row.append(name,bar,score);$('classification').append(row)}}if(item.draft){$('draft-title').textContent=item.draft.title;$('draft-body').textContent=item.draft.body;$('source').href=item.draft.source_url}$('json').textContent=JSON.stringify(item,null,2)}
async function refresh(){data=await api('runs');preview();renderHistory()}
async function busy(button,task){button.disabled=true;try{await task()}catch(error){message(error.message)}finally{button.disabled=false}}
$('fixture').onchange=preview;
$('run').onclick=()=>busy($('run'),async()=>{message('Обрабатываем материал…');const result=await api('runs','POST',{fixture:$('fixture').value,simulate_error:$('failure').checked});await refresh();show(result);message(result.status==='failed'?'Смоделирован сбой. Повторите обработку этого же материала.':'Черновик подготовлен. Проверьте источник перед публикацией.');$('result').scrollIntoView({block:'start',behavior:'smooth'})});
$('retry').onclick=()=>busy($('retry'),async()=>{const result=await api('runs/'+active.id+'/retry','POST');await refresh();show(result);message('Повтор завершён: тот же материал получил черновик. Новая запись не создавалась.')});
$('reset').onclick=()=>busy($('reset'),async()=>{await api('runs','DELETE');await refresh();active=null;$('empty').hidden=false;$('result').hidden=true;$('failure').checked=false;message('Ваши материалы удалены. Другие сессии не затронуты.')});
refresh().catch(error=>message(error.message));
